<?php

return [
    /*
     * Module Registry — organized by business type with free/paid tiers.
     * Each module knows its price and which business types it belongs to.
     */
    'content' => [
        'label' => 'Content / Pages',
        'icon' => 'ti-file-text',
        'nav_section' => 'Content',
        'route' => 'tenant.content',
        'description' => 'About text, gallery images, and contact details.',
        'price' => 0,
        'free' => true,
        'business_types' => ['info', 'shopping', 'restaurant', 'business'],
    ],
    'catalog' => [
        'label' => 'Product Catalog',
        'icon' => 'ti-box',
        'nav_section' => 'Store',
        'route' => 'tenant.catalog',
        'description' => 'Product catalog with photos, pricing, and buy buttons.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping', 'restaurant'],
    ],
    'payments' => [
        'label' => 'Payment Settings',
        'icon' => 'ti-credit-card',
        'nav_section' => 'Store',
        'route' => 'tenant.payments',
        'description' => 'Razorpay / Stripe / Custom gateway configuration.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping', 'restaurant'],
    ],
    'orders' => [
        'label' => 'Orders',
        'icon' => 'ti-truck-delivery',
        'nav_section' => 'Store',
        'route' => 'tenant.orders',
        'description' => 'View incoming orders and update status.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping', 'restaurant'],
    ],
    'reservations' => [
        'label' => 'Reservations',
        'icon' => 'ti-calendar-event',
        'nav_section' => 'Store',
        'route' => 'tenant.reservations',
        'description' => 'Table booking requests from the storefront.',
        'price' => 0,
        'free' => true,
        'business_types' => ['restaurant'],
    ],
    'services' => [
        'label' => 'Services',
        'icon' => 'ti-briefcase-2',
        'nav_section' => 'Business',
        'route' => 'tenant.services',
        'description' => 'Services you offer, with optional pricing.',
        'price' => 0,
        'free' => true,
        'business_types' => ['business'],
    ],
    'testimonials' => [
        'label' => 'Testimonials',
        'icon' => 'ti-quote',
        'nav_section' => 'Business',
        'route' => 'tenant.testimonials',
        'description' => 'Client quotes and reviews shown on your site.',
        'price' => 0,
        'free' => true,
        'business_types' => ['business'],
    ],
    'blog' => [
        'label' => 'Blog',
        'icon' => 'ti-news',
        'nav_section' => 'Business',
        'route' => 'tenant.blog',
        'description' => 'Articles and news posts for your site.',
        'price' => 0,
        'free' => true,
        'business_types' => ['business'],
    ],

    // ===== PAID ADD-ON MODULES =====
    'analytics_pro' => [
        'label' => 'Analytics Pro',
        'icon' => 'ti-chart-bar',
        'nav_section' => 'Business',
        'route' => 'tenant.analytics',
        'description' => 'Advanced analytics: heatmaps, funnels, cohort analysis, custom reports.',
        'price' => 1999,
        'free' => false,
        'business_types' => ['info', 'shopping', 'restaurant', 'business'],
    ],
    'whatsapp_automation' => [
        'label' => 'WhatsApp Automation',
        'icon' => 'ti-brand-whatsapp',
        'nav_section' => 'Business',
        'route' => 'tenant.whatsapp',
        'description' => 'Auto-replies, broadcast messages, abandoned cart recovery via WhatsApp.',
        'price' => 2999,
        'free' => false,
        'business_types' => ['shopping', 'restaurant', 'business'],
    ],
    'ai_agent' => [
        'label' => 'AI Assistant',
        'icon' => 'ti-robot-face',
        'nav_section' => 'Business',
        'route' => 'tenant.ai-agent',
        'description' => 'GPT-powered chatbot for customer support and sales on your storefront.',
        'price' => 3999,
        'free' => false,
        'business_types' => ['shopping', 'restaurant', 'business'],
    ],
    'email_marketing' => [
        'label' => 'Email Marketing',
        'icon' => 'ti-mail',
        'nav_section' => 'Business',
        'route' => 'tenant.email-marketing',
        'description' => 'Newsletter campaigns, drip sequences, and automated follow-ups.',
        'price' => 2499,
        'free' => false,
        'business_types' => ['shopping', 'business'],
    ],
    'loyalty_program' => [
        'label' => 'Loyalty Program',
        'icon' => 'ti-gift',
        'nav_section' => 'Business',
        'route' => 'tenant.loyalty',
        'description' => 'Points, rewards, referral program, and VIP tiers for repeat customers.',
        'price' => 2999,
        'free' => false,
        'business_types' => ['shopping', 'restaurant'],
    ],
    'multi_location' => [
        'label' => 'Multi-Location',
        'icon' => 'ti-map-pin',
        'nav_section' => 'Business',
        'route' => 'tenant.locations',
        'description' => 'Manage multiple branches with shared inventory and centralized reporting.',
        'price' => 4999,
        'free' => false,
        'business_types' => ['shopping', 'restaurant', 'business'],
    ],
    'subscription_billing' => [
        'label' => 'Subscription Billing',
        'icon' => 'ti-credit-card',
        'nav_section' => 'Store',
        'route' => 'tenant.subscriptions',
        'description' => 'Recurring payments, trial periods, dunning management, and invoices.',
        'price' => 3999,
        'free' => false,
        'business_types' => ['shopping', 'business'],
    ],
    'pos_integration' => [
        'label' => 'POS Integration',
        'icon' => 'ti-device-desktop',
        'nav_section' => 'Store',
        'route' => 'tenant.pos',
        'description' => 'Sync with Square, Toast, Clover, or custom POS for unified inventory.',
        'price' => 4999,
        'free' => false,
        'business_types' => ['shopping', 'restaurant'],
    ],
];