<?php

/**
 * Business Feature Bundles — defines what features each business type gets.
 *
 * Each feature has:
 *   toggleable = true  → admin can toggle on/off per tenant
 *   price > 0          → paid add-on
 *   future = true      → not built yet, shows "Coming Soon"
 */

return [

    'bundles' => [

        'school' => [
            'label' => 'School',
            'icon' => 'ti-school',
            'description' => 'Professional school website with all essential sections included free.',
            'free' => [
                ['key' => 'hero', 'name' => 'Hero Banner', 'icon' => 'ti-photo', 'description' => 'Full-width banner with school name, motto, and admission CTA.', 'toggleable' => true, 'price' => 0],
                ['key' => 'stats', 'name' => 'School Highlights', 'icon' => 'ti-star', 'description' => 'Quick highlight cards — Experienced Faculty, Quality Education, etc.', 'toggleable' => true, 'price' => 0],
                ['key' => 'about', 'name' => 'About School', 'icon' => 'ti-info-circle', 'description' => 'School history, vision, mission, core values, and principal message.', 'toggleable' => true, 'price' => 0],
                ['key' => 'academics', 'name' => 'Academics', 'icon' => 'ti-book', 'description' => 'Curriculum, classes, subjects, school timings, and examination system.', 'toggleable' => true, 'price' => 0],
                ['key' => 'admissions', 'name' => 'Admissions', 'icon' => 'ti-clipboard', 'description' => 'Admission process, eligibility, fee structure, documents, FAQs.', 'toggleable' => true, 'price' => 0],
                ['key' => 'faculty', 'name' => 'Faculty & Staff', 'icon' => 'ti-users', 'description' => 'Principal, teachers, and staff profiles with photos and qualifications.', 'toggleable' => true, 'price' => 0],
                ['key' => 'student_life', 'name' => 'Student Life', 'icon' => 'ti-mood-happy', 'description' => 'Clubs, sports, cultural activities, competitions, and events.', 'toggleable' => true, 'price' => 0],
                ['key' => 'facilities', 'name' => 'Facilities', 'icon' => 'ti-building', 'description' => 'Smart classrooms, library, computer lab, science lab, playground, transport.', 'toggleable' => true, 'price' => 0],
                ['key' => 'gallery', 'name' => 'Gallery', 'icon' => 'ti-photo', 'description' => 'Photo albums — campus, classrooms, events, sports, cultural.', 'toggleable' => true, 'price' => 0],
                ['key' => 'news', 'name' => 'News & Events', 'icon' => 'ti-news', 'description' => 'School news, circulars, holiday notices, and upcoming events.', 'toggleable' => true, 'price' => 0],
                ['key' => 'achievements', 'name' => 'Achievements', 'icon' => 'ti-trophy', 'description' => 'Student toppers, sports winners, board results, awards.', 'toggleable' => true, 'price' => 0],
                ['key' => 'testimonials', 'name' => 'Testimonials', 'icon' => 'ti-quote', 'description' => 'Parent and student reviews with ratings.', 'toggleable' => true, 'price' => 0],
                ['key' => 'downloads', 'name' => 'Downloads', 'icon' => 'ti-file-download', 'description' => 'Admission forms, fee structure, prospectus, calendar, circulars.', 'toggleable' => true, 'price' => 0],
                ['key' => 'certificates', 'name' => 'Certificates & Recognition', 'icon' => 'ti-certificate', 'description' => 'Government recognition, affiliation, safety certificates.', 'toggleable' => true, 'price' => 0],
                ['key' => 'contact', 'name' => 'Contact', 'icon' => 'ti-map-pin', 'description' => 'Address, phone, email, office hours, Google Map, WhatsApp button.', 'toggleable' => true, 'price' => 0],
            ],
            // Keep the website-management essentials in the free bundle.
            // Student/parent portals and ERP are intentionally outside this product.
            'pro' => [],
            'premium' => [],
        ],

        'shopping' => [
            'label' => 'Shopping / Store',
            'icon' => 'ti-shopping-cart',
            'description' => 'Full e-commerce storefront with catalog, cart, and checkout.',
            'free' => [
                ['key' => 'catalog', 'name' => 'Product Catalog', 'icon' => 'ti-box', 'description' => 'Product listings with pricing, descriptions, slugs, active status, featured flags, SKU, and product notes.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported Upgrade'],
                ['key' => 'product_categories', 'name' => 'Product Categories', 'icon' => 'ti-category', 'description' => 'Reusable category records instead of one-off text labels.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported New'],
                ['key' => 'product_gallery', 'name' => 'Product Gallery', 'icon' => 'ti-photo', 'description' => 'Cover image plus multiple product gallery images.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported Upgrade'],
                ['key' => 'content', 'name' => 'Store Content', 'icon' => 'ti-file-text', 'description' => 'About text, gallery images, contact details, logo, and banner.', 'toggleable' => true, 'price' => 0],
                ['key' => 'cart_checkout', 'keys' => ['cart', 'checkout', 'payments'], 'name' => 'Cart & Checkout', 'icon' => 'ti-brand-whatsapp', 'description' => 'Cart, COD, WhatsApp checkout, order placement, and basic payment settings.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported Upgrade'],
                ['key' => 'orders', 'name' => 'Order Management', 'icon' => 'ti-truck-delivery', 'description' => 'View orders, update status, confirmation, tracking, customer details, notes, and payment status.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported Upgrade'],
                ['key' => 'product_collections', 'name' => 'Collections', 'icon' => 'ti-folders', 'description' => 'Reusable product collections such as Signature Series, New Arrivals, and seasonal edits.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported New'],
                ['key' => 'inventory', 'name' => 'Inventory', 'icon' => 'ti-packages', 'description' => 'Product and variant stock, low-stock indicators, and checkout stock reduction.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported New'],
                ['key' => 'search_filters', 'name' => 'Search & Filters', 'icon' => 'ti-filter', 'description' => 'Search products, filter by category or collection, and sort the catalog.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported Upgrade'],
                ['key' => 'marketing_sections', 'name' => 'Marketing Sections', 'icon' => 'ti-layout-grid-add', 'description' => 'Homepage product sections such as trending, new arrivals, editor picks, and testimonials.', 'toggleable' => true, 'price' => 0, 'import_type' => 'Imported New'],
                ['key' => 'wishlist', 'name' => 'Wishlist', 'icon' => 'ti-heart', 'description' => 'Let shoppers save products for later and return to buy.', 'toggleable' => true, 'price' => 0],
            ],
            'pro' => [
                ['key' => 'product_options', 'keys' => ['product_colors', 'product_sizes', 'variants'], 'name' => 'Colors, Sizes & Variants', 'icon' => 'ti-list-tree', 'description' => 'Color swatches, sizes, variant SKU, variant stock, and variant price overrides.', 'toggleable' => true, 'price' => 1499, 'import_type' => 'Imported New'],
                ['key' => 'product_videos', 'name' => 'Product Videos', 'icon' => 'ti-video', 'description' => 'Upload product videos for product detail pages and future premium themes.', 'toggleable' => true, 'price' => 799, 'import_type' => 'Imported New'],
                ['key' => 'customer_accounts', 'name' => 'Customer Accounts', 'icon' => 'ti-user-circle', 'description' => 'Customer login, saved profile, saved addresses, and order history.', 'toggleable' => true, 'price' => 1499],
                ['key' => 'razorpay_gateway', 'name' => 'Razorpay Gateway', 'icon' => 'ti-credit-card-pay', 'description' => 'Accept cards, UPI, netbanking, and wallet payments with the store owner Razorpay account.', 'toggleable' => true, 'price' => 999],
                ['key' => 'reviews', 'name' => 'Product Reviews', 'icon' => 'ti-star', 'description' => 'Customer ratings and reviews on product pages.', 'toggleable' => true, 'price' => 799],
                ['key' => 'coupons', 'name' => 'Coupons & Discounts', 'icon' => 'ti-ticket', 'description' => 'Create discount codes, promotional offers, and campaign coupons.', 'toggleable' => true, 'price' => 1299],
                ['key' => 'shipping_rules', 'name' => 'Shipping Rules', 'icon' => 'ti-truck-delivery', 'description' => 'Delivery fee rules, free shipping thresholds, and pincode rules.', 'toggleable' => true, 'price' => 999],
                ['key' => 'gst_invoice', 'name' => 'GST Invoice', 'icon' => 'ti-file-invoice', 'description' => 'Tax calculation and printable/downloadable GST invoices.', 'toggleable' => true, 'price' => 1499],
                ['key' => 'abandoned_cart', 'name' => 'Abandoned Cart Recovery', 'icon' => 'ti-shopping-cart-exclamation', 'description' => 'Recover incomplete carts with WhatsApp/email reminders.', 'toggleable' => true, 'price' => 1499],
                ['key' => 'loyalty_rewards', 'name' => 'Loyalty & Rewards', 'icon' => 'ti-gift', 'description' => 'Points, reward rules, referrals, and repeat purchase incentives.', 'toggleable' => true, 'price' => 1999],
                ['key' => 'subscription_products', 'name' => 'Subscription Products', 'icon' => 'ti-refresh', 'description' => 'Sell recurring subscriptions and repeat-order products.', 'toggleable' => true, 'price' => 2999],
                ['key' => 'advanced_analytics', 'name' => 'Advanced Store Analytics', 'icon' => 'ti-chart-histogram', 'description' => 'Sales trends, product performance, conversion reports, and customer insights.', 'toggleable' => true, 'price' => 1999],
                ['key' => 'seo_booster', 'name' => 'SEO Booster', 'icon' => 'ti-seo', 'description' => 'Product SEO metadata, social preview tags, sitemap, and search snippets.', 'toggleable' => true, 'price' => 999],
                ['key' => 'bulk_import_export', 'name' => 'Bulk Import / Export', 'icon' => 'ti-file-spreadsheet', 'description' => 'Import and export products, variants, prices, and inventory using spreadsheets.', 'toggleable' => true, 'price' => 1499],
                ['key' => 'jem_preloader', 'name' => 'Premium Store Preloader', 'icon' => 'ti-loader-3', 'description' => 'Luxury animated storefront preloader and entrance effect for custom premium themes.', 'toggleable' => true, 'price' => 799],
            ],
            'premium' => [
                ['key' => 'pos_integration', 'name' => 'POS Integration', 'icon' => 'ti-device-desktop', 'description' => 'Sync store products and inventory with supported POS systems.', 'toggleable' => true, 'price' => 4999],
            ],
        ],

        'restaurant' => [
            'label' => 'Restaurant',
            'icon' => 'ti-utensils',
            'description' => 'Menu-focused site with online ordering and table reservations.',
            'free' => [
                ['key' => 'menu', 'name' => 'Menu / Catalog', 'icon' => 'ti-book', 'description' => 'Menu items with photos, prices, and categories.', 'toggleable' => true, 'price' => 0],
                ['key' => 'reservations', 'name' => 'Table Reservations', 'icon' => 'ti-calendar-event', 'description' => 'Online table booking requests from storefront.', 'toggleable' => true, 'price' => 0],
                ['key' => 'orders', 'name' => 'Orders', 'icon' => 'ti-truck-delivery', 'description' => 'Incoming orders with status management.', 'toggleable' => true, 'price' => 0],
                ['key' => 'payments', 'name' => 'Payment Settings', 'icon' => 'ti-credit-card', 'description' => 'Razorpay, COD, or custom gateway config.', 'toggleable' => true, 'price' => 0],
                ['key' => 'gallery', 'name' => 'Gallery', 'icon' => 'ti-photo', 'description' => 'Food photos, ambiance, and event images.', 'toggleable' => true, 'price' => 0],
                ['key' => 'content', 'name' => 'Content Pages', 'icon' => 'ti-file-text', 'description' => 'About, contact details, and opening hours.', 'toggleable' => true, 'price' => 0],
            ],
            'pro' => [
                ['key' => 'online_ordering', 'name' => 'Online Ordering', 'icon' => 'ti-shopping-cart', 'description' => 'Full food ordering with cart and delivery options.', 'toggleable' => true, 'price' => 1499],
                ['key' => 'table_booking', 'name' => 'Advanced Table Booking', 'icon' => 'ti-calendar', 'description' => 'Time slots, party size, special requests.', 'toggleable' => true, 'price' => 999],
                ['key' => 'events', 'name' => 'Events & Offers', 'icon' => 'ti-speakerphone', 'description' => 'Promote events, happy hours, and special offers.', 'toggleable' => true, 'price' => 799],
            ],
            'premium' => [
                ['key' => 'delivery', 'name' => 'Delivery Tracking', 'icon' => 'ti-route', 'description' => 'Real-time order tracking for customers.', 'toggleable' => false, 'price' => 2999, 'future' => true],
                ['key' => 'loyalty', 'name' => 'Loyalty Program', 'icon' => 'ti-gift', 'description' => 'Points, rewards, and referral system.', 'toggleable' => false, 'price' => 2999],
                ['key' => 'multi_branch', 'name' => 'Multi-Branch', 'icon' => 'ti-map-pin', 'description' => 'Manage multiple locations with centralized menu.', 'toggleable' => false, 'price' => 4999, 'future' => true],
            ],
        ],

        'business' => [
            'label' => 'Portfolio / Business',
            'icon' => 'ti-briefcase-2',
            'description' => 'Professional site with services, testimonials, and blog.',
            'free' => [
                ['key' => 'services', 'name' => 'Services', 'icon' => 'ti-briefcase-2', 'description' => 'Service listings with descriptions and pricing.', 'toggleable' => true, 'price' => 0],
                ['key' => 'testimonials', 'name' => 'Testimonials', 'icon' => 'ti-quote', 'description' => 'Client quotes and reviews with ratings.', 'toggleable' => true, 'price' => 0],
                ['key' => 'blog', 'name' => 'Blog', 'icon' => 'ti-news', 'description' => 'Articles and news posts for SEO and updates.', 'toggleable' => true, 'price' => 0],
                ['key' => 'content', 'name' => 'Content Pages', 'icon' => 'ti-file-text', 'description' => 'About text, gallery images, and contact details.', 'toggleable' => true, 'price' => 0],
                ['key' => 'case_studies', 'name' => 'Case Studies', 'icon' => 'ti-file-text', 'description' => 'Project showcases with client results.', 'toggleable' => true, 'price' => 0],
                ['key' => 'team', 'name' => 'Team Profiles', 'icon' => 'ti-users', 'description' => 'Team profiles with roles, photos, and bios.', 'toggleable' => true, 'price' => 0],
                ['key' => 'careers', 'name' => 'Careers', 'icon' => 'ti-badge', 'description' => 'Job listings and application capture.', 'toggleable' => true, 'price' => 0],
                ['key' => 'newsletter', 'name' => 'Newsletter Signup', 'icon' => 'ti-mail', 'description' => 'Subscriber capture and dashboard list.', 'toggleable' => true, 'price' => 0],
                ['key' => 'enquiries', 'name' => 'Enquiry Inbox', 'icon' => 'ti-inbox', 'description' => 'Public contact form and enquiry tracking.', 'toggleable' => true, 'price' => 0],
            ],
            'pro' => [],
            'premium' => [],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Module Keys (backward compatibility with Tenant::hasModule)
    |--------------------------------------------------------------------------
    */
    'content' => [
        'label' => 'Content / Pages',
        'icon' => 'ti-file-text',
        'nav_section' => 'Content & Settings',
        'route' => 'tenant.content',
        'description' => 'About text, gallery images, and contact details.',
        'price' => 0,
        'free' => true,
        'business_types' => ['school', 'shopping', 'restaurant', 'business'],
    ],
    // School website sections. These are deliberately content-only features;
    // they do not imply attendance, fees, student accounts, or ERP workflows.
    'hero' => ['label' => 'Hero Banner', 'icon' => 'ti-photo', 'description' => 'Homepage welcome banner and admissions call to action.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'stats' => ['label' => 'School Highlights', 'icon' => 'ti-star', 'description' => 'Homepage highlight and achievement counters.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'about' => ['label' => 'About School', 'icon' => 'ti-info-circle', 'description' => 'School story, vision, mission, and principal message.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'academics' => ['label' => 'Academics', 'icon' => 'ti-book', 'description' => 'Classes, curriculum, timings, and academic information.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'admissions' => ['label' => 'Admissions', 'icon' => 'ti-clipboard', 'description' => 'Admission process, eligibility, documents, and FAQs.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'faculty' => ['label' => 'Faculty & Staff', 'icon' => 'ti-users', 'description' => 'Manage teacher and staff profiles.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'student_life' => ['label' => 'Student Life', 'icon' => 'ti-mood-happy', 'description' => 'Activities, clubs, sports, and co-curricular information.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'facilities' => ['label' => 'Facilities', 'icon' => 'ti-building', 'description' => 'Campus and facility highlights.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'gallery' => ['label' => 'Gallery', 'icon' => 'ti-photo', 'description' => 'Campus, classroom, event, and activity images.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'news' => ['label' => 'News & Notices', 'icon' => 'ti-news', 'description' => 'School announcements, news, and upcoming events.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'achievements' => ['label' => 'Achievements', 'icon' => 'ti-trophy', 'description' => 'Results, awards, winners, and school milestones.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'downloads' => ['label' => 'Downloads', 'icon' => 'ti-file-download', 'description' => 'Prospectus, calendar, circulars, and public forms.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'certificates' => ['label' => 'Recognition', 'icon' => 'ti-certificate', 'description' => 'Affiliation, recognition, and public certificates.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'contact' => ['label' => 'Contact', 'icon' => 'ti-map-pin', 'description' => 'Address, office hours, phone, email, and contact links.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'why_choose' => ['label' => 'Why Choose Us', 'icon' => 'ti-sparkles', 'description' => 'School strengths and trust-building cards.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'map' => ['label' => 'Location Map', 'icon' => 'ti-map', 'description' => 'Public location map embed.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'enquiry_form' => ['label' => 'Admission Enquiries', 'icon' => 'ti-inbox', 'route' => 'tenant.business-inbox', 'description' => 'Public admission enquiry form and inbox.', 'price' => 0, 'free' => true, 'business_types' => ['school']],
    'catalog' => [
        'label' => 'Product Catalog',
        'icon' => 'ti-box',
        'nav_section' => 'Product Management',
        'route' => 'tenant.catalog',
        'description' => 'Product catalog with photos, pricing, and buy buttons.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping', 'restaurant'],
    ],
    'product_categories' => [
        'label' => 'Product Categories',
        'icon' => 'ti-category',
        'description' => 'Structured product categories for shopping tenants.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'product_gallery' => [
        'label' => 'Product Gallery',
        'icon' => 'ti-photo',
        'description' => 'Multiple product images and cover image.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'product_collections' => [
        'label' => 'Collections',
        'icon' => 'ti-folders',
        'nav_section' => 'Product Management',
        'route' => 'tenant.collections',
        'description' => 'Reusable product collections for storefront sections.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'product_colors' => [
        'label' => 'Product Colors',
        'icon' => 'ti-palette',
        'description' => 'Color swatches and color-specific images.',
        'price' => 0,
        'business_types' => ['shopping'],
    ],
    'product_sizes' => [
        'label' => 'Product Sizes',
        'icon' => 'ti-ruler',
        'description' => 'Reusable size options per product.',
        'price' => 0,
        'business_types' => ['shopping'],
    ],
    'variants' => [
        'label' => 'Product Options',
        'icon' => 'ti-adjustments',
        'nav_section' => 'Product Management',
        'route' => 'tenant.attributes',
        'description' => 'Color/size variant SKU, stock, and price override.',
        'price' => 1499,
        'business_types' => ['shopping'],
    ],
    'inventory' => [
        'label' => 'Inventory',
        'icon' => 'ti-packages',
        'nav_section' => 'Product Management',
        'route' => 'tenant.inventory',
        'description' => 'Stock quantity and checkout stock reduction.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'product_videos' => [
        'label' => 'Product Videos',
        'icon' => 'ti-video',
        'description' => 'Product video uploads.',
        'price' => 799,
        'business_types' => ['shopping'],
    ],
    'jem_preloader' => [
        'label' => 'Premium Store Preloader',
        'icon' => 'ti-loader-3',
        'nav_section' => 'Storefront',
        'route' => 'tenant.theme',
        'description' => 'Luxury animated storefront preloader and entrance effect for custom premium themes.',
        'price' => 799,
        'business_types' => ['shopping'],
    ],
    'search_filters' => [
        'label' => 'Search & Filters',
        'icon' => 'ti-filter',
        'description' => 'Search, category filters, collection filters, and sorting.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'marketing_sections' => [
        'label' => 'Marketing Sections',
        'icon' => 'ti-layout-grid-add',
        'nav_section' => 'Marketing',
        'route' => 'tenant.marketing-sections',
        'description' => 'Homepage merchandising sections and promotional blocks.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'cart' => [
        'label' => 'Shopping Cart',
        'icon' => 'ti-shopping-cart',
        'description' => 'Customer cart with quantity updates and item removal.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'checkout' => [
        'label' => 'Checkout',
        'icon' => 'ti-brand-whatsapp',
        'description' => 'Customer checkout with COD, WhatsApp order placement, and prepaid order support.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'payments' => [
        'label' => 'Payment Settings',
        'icon' => 'ti-credit-card',
        'nav_section' => 'Payments',
        'route' => 'tenant.payments',
        'description' => 'Basic payment settings, COD, custom instructions, and WhatsApp checkout fallback.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping', 'restaurant'],
    ],
    'orders' => [
        'label' => 'Orders',
        'icon' => 'ti-truck-delivery',
        'nav_section' => 'Orders',
        'route' => 'tenant.orders',
        'description' => 'View incoming orders and update status.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping', 'restaurant'],
    ],
    'reservations' => [
        'label' => 'Reservations',
        'icon' => 'ti-calendar-event',
        'nav_section' => 'Store',
        'route' => 'tenant.reservations',
        'description' => 'Table booking requests from the storefront.',
        'price' => 0,
        'free' => true,
        'business_types' => ['restaurant'],
    ],
    'services' => [
        'label' => 'Services',
        'icon' => 'ti-briefcase-2',
        'nav_section' => 'Business',
        'route' => 'tenant.services',
        'description' => 'Services you offer, with optional pricing.',
        'price' => 0,
        'free' => true,
        'business_types' => ['business'],
    ],
    'testimonials' => [
        'label' => 'Testimonials',
        'icon' => 'ti-quote',
        'nav_section' => 'Business',
        'route' => 'tenant.testimonials',
        'description' => 'Client quotes and reviews shown on your site.',
        'price' => 0,
        'free' => true,
        'business_types' => ['business'],
    ],
    'blog' => [
        'label' => 'Blog',
        'icon' => 'ti-news',
        'nav_section' => 'Business',
        'route' => 'tenant.blog',
        'description' => 'Articles and news posts for your site.',
        'price' => 0,
        'free' => true,
        'business_types' => ['business'],
    ],
    'analytics_pro' => [
        'label' => 'Analytics Pro',
        'icon' => 'ti-chart-bar',
        'nav_section' => 'Business',
        'route' => 'tenant.analytics',
        'description' => 'Advanced analytics: heatmaps, funnels, cohort analysis.',
        'price' => 1999,
        'free' => false,
        'business_types' => ['school', 'shopping', 'restaurant', 'business'],
    ],
    'wishlist' => [
        'label' => 'Wishlist',
        'icon' => 'ti-heart',
        'description' => 'Customer saved products and wishlist buying intent.',
        'price' => 0,
        'free' => true,
        'business_types' => ['shopping'],
    ],
    'customer_accounts' => [
        'label' => 'Customers',
        'icon' => 'ti-user-circle',
        'nav_section' => 'Customers',
        'route' => 'tenant.customers',
        'description' => 'Customer login, profiles, addresses, and order history.',
        'price' => 1499,
        'business_types' => ['shopping'],
    ],
    'razorpay_gateway' => [
        'label' => 'Razorpay Gateway',
        'icon' => 'ti-credit-card-pay',
        'description' => 'Online card, UPI, wallet, and netbanking payments.',
        'price' => 999,
        'business_types' => ['shopping'],
    ],
    'reviews' => [
        'label' => 'Product Reviews',
        'icon' => 'ti-star',
        'nav_section' => 'Customers',
        'route' => 'tenant.reviews',
        'description' => 'Product ratings and customer review moderation.',
        'price' => 799,
        'business_types' => ['shopping'],
    ],
    'coupons' => [
        'label' => 'Coupons & Discounts',
        'icon' => 'ti-ticket',
        'nav_section' => 'Marketing',
        'route' => 'tenant.coupons',
        'description' => 'Discount codes and promotional pricing campaigns.',
        'price' => 1299,
        'business_types' => ['shopping'],
    ],
    'shipping_rules' => [
        'label' => 'Shipping Rules',
        'icon' => 'ti-truck-delivery',
        'nav_section' => 'Orders',
        'route' => 'tenant.shipping-rules',
        'description' => 'Delivery fees, free shipping thresholds, and pincode rules.',
        'price' => 999,
        'business_types' => ['shopping'],
    ],
    'gst_invoice' => [
        'label' => 'GST Invoice',
        'icon' => 'ti-file-invoice',
        'nav_section' => 'Payments',
        'route' => 'tenant.commerce-feature',
        'description' => 'GST tax calculation and printable/downloadable invoices.',
        'price' => 1499,
        'business_types' => ['shopping'],
    ],
    'abandoned_cart' => [
        'label' => 'Abandoned Cart Recovery',
        'icon' => 'ti-shopping-cart-exclamation',
        'nav_section' => 'Marketing',
        'route' => 'tenant.commerce-feature',
        'description' => 'Cart recovery reminders by WhatsApp or email.',
        'price' => 1499,
        'business_types' => ['shopping'],
    ],
    'loyalty_rewards' => [
        'label' => 'Loyalty & Rewards',
        'icon' => 'ti-gift',
        'nav_section' => 'Marketing',
        'route' => 'tenant.commerce-feature',
        'description' => 'Points, referral rewards, and loyalty campaigns.',
        'price' => 1999,
        'business_types' => ['shopping'],
    ],
    'subscription_products' => [
        'label' => 'Subscription Products',
        'icon' => 'ti-refresh',
        'route' => 'tenant.commerce-feature',
        'description' => 'Recurring product subscriptions and repeat-order plans.',
        'price' => 2999,
        'business_types' => ['shopping'],
    ],
    'advanced_analytics' => [
        'label' => 'Advanced Store Analytics',
        'icon' => 'ti-chart-histogram',
        'nav_section' => 'Growth',
        'route' => 'tenant.commerce-feature',
        'description' => 'Sales reports, conversion insights, and product analytics.',
        'price' => 1999,
        'business_types' => ['shopping'],
    ],
    'seo_booster' => [
        'label' => 'SEO Booster',
        'icon' => 'ti-seo',
        'nav_section' => 'Growth',
        'route' => 'tenant.seo',
        'description' => 'Product SEO metadata, social previews, and sitemap tools.',
        'price' => 999,
        'business_types' => ['shopping'],
    ],
    'bulk_import_export' => [
        'label' => 'Bulk Import / Export',
        'icon' => 'ti-file-spreadsheet',
        'nav_section' => 'Product Management',
        'route' => 'tenant.commerce-feature',
        'description' => 'Spreadsheet import/export for products, variants, and stock.',
        'price' => 1499,
        'business_types' => ['shopping'],
    ],
    'pos_integration' => [
        'label' => 'POS Integration',
        'icon' => 'ti-device-desktop',
        'nav_section' => 'Payments',
        'route' => 'tenant.commerce-feature',
        'description' => 'Sync products and inventory with supported POS systems.',
        'price' => 4999,
        'business_types' => ['shopping'],
    ],
];
