<style>
    .biz-dash{display:grid;gap:18px}.biz-hero,.biz-panel,.biz-stat{background:#fff;border:1px solid var(--border-card);border-radius:10px;box-shadow:0 12px 30px rgba(15,23,42,.055)}.biz-hero{display:grid;grid-template-columns:1fr auto;gap:22px;align-items:center;padding:24px;border-top:4px solid #0f766e}.biz-kicker{color:#0f766e;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:1px}.biz-hero h2{font:900 27px/1.15 'Syne',sans-serif;margin:7px 0}.biz-hero p{color:var(--text-muted);margin:0;max-width:720px}.biz-actions{display:flex;gap:8px;flex-wrap:wrap}.biz-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.biz-stat{padding:17px;min-height:116px}.biz-stat span{color:var(--text-muted);font-size:11px;font-weight:900;text-transform:uppercase}.biz-stat strong{display:block;font-size:27px;margin-top:17px}.biz-main{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.biz-panel{padding:18px}.biz-panel h3{margin:0 0 14px;font-size:15px}.biz-row{display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid #edf2f7}.biz-row:last-child{border:0}.biz-icon{width:36px;height:36px;border-radius:8px;background:#e8f5f1;color:#0f766e;display:grid;place-items:center;flex:none}.biz-row-main{min-width:0;flex:1}.biz-row-main strong{display:block;font-size:12.5px}.biz-row-main span{display:block;color:var(--text-muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.biz-status{font-size:10px;font-weight:900;color:#047857;background:#ecfdf5;padding:5px 7px;border-radius:5px}.biz-tools{display:grid;grid-template-columns:1fr 1fr;gap:8px}.biz-tool{display:flex;gap:9px;align-items:center;padding:13px;border:1px solid #e4ebf3;border-radius:8px;text-decoration:none;color:var(--text-primary);font-size:12px;font-weight:900}.biz-tool i{color:#0f766e;font-size:18px}@media(max-width:1000px){.biz-grid{grid-template-columns:1fr 1fr}.biz-main{grid-template-columns:1fr}}@media(max-width:650px){.biz-hero{grid-template-columns:1fr}.biz-grid,.biz-tools{grid-template-columns:1fr}}
</style>
<div class="biz-dash">
    <section class="biz-hero"><div><div class="biz-kicker">Business Website Console</div><h2>{{ $tenant->name }} overview</h2><p>Manage your public website, track new opportunities, publish proof of work, and keep your company information current.</p></div><div class="biz-actions"><a class="eos-btn eos-btn-primary" href="{{ route('tenant.business-inbox') }}"><i class="ti ti-inbox"></i> View Enquiries</a><a class="eos-btn eos-btn-secondary" href="{{ url('/') }}" target="_blank"><i class="ti ti-external-link"></i> View Website</a></div></section>
    <section class="biz-grid">
        <div class="biz-stat"><span>New enquiries</span><strong>{{ $businessStats['new_enquiries'] ?? 0 }}</strong></div>
        <div class="biz-stat"><span>Published services</span><strong>{{ $businessStats['services'] ?? 0 }}</strong></div>
        <div class="biz-stat"><span>Case studies</span><strong>{{ $businessStats['case_studies'] ?? 0 }}</strong></div>
        <div class="biz-stat"><span>Subscribers</span><strong>{{ $businessStats['subscribers'] ?? 0 }}</strong></div>
    </section>
    <section class="biz-main">
        <div class="biz-panel"><h3>Latest Enquiries</h3>@forelse($recentEnquiries as $enquiry)<div class="biz-row"><div class="biz-icon"><i class="ti ti-message"></i></div><div class="biz-row-main"><strong>{{ $enquiry->subject ?: 'Website enquiry' }}</strong><span>{{ $enquiry->name }} · {{ $enquiry->email }} · {{ $enquiry->created_at->diffForHumans() }}</span></div><span class="biz-status">{{ ucfirst($enquiry->status) }}</span></div>@empty<div class="eos-empty">No enquiries yet. New website leads and job applications will appear here.</div>@endforelse</div>
        <div class="biz-panel"><h3>Website Content</h3><div class="biz-tools">
            <a class="biz-tool" href="{{ route('tenant.services') }}"><i class="ti ti-briefcase"></i> Services ({{ $businessStats['services'] ?? 0 }})</a>
            <a class="biz-tool" href="{{ route('tenant.business-content.index',['type'=>'case-studies']) }}"><i class="ti ti-file-text"></i> Work ({{ $businessStats['case_studies'] ?? 0 }})</a>
            <a class="biz-tool" href="{{ route('tenant.business-content.index',['type'=>'team']) }}"><i class="ti ti-users"></i> Team ({{ $businessStats['team'] ?? 0 }})</a>
            <a class="biz-tool" href="{{ route('tenant.blog') }}"><i class="ti ti-news"></i> Posts ({{ $businessStats['posts'] ?? 0 }})</a>
            <a class="biz-tool" href="{{ route('tenant.business-content.index',['type'=>'careers']) }}"><i class="ti ti-id-badge-2"></i> Careers ({{ $businessStats['careers'] ?? 0 }})</a>
            <a class="biz-tool" href="{{ route('tenant.content') }}"><i class="ti ti-building"></i> Business Details</a>
        </div></div>
    </section>
</div>
